ardriveapp/ardrive-core-js

- src/sharing_private.ts
Changes the function to take a driveKey and fileId as arguments instead of generating them from the user object and file entity.
> refactor: change create arfs private file sharing link arguments

- .github/workflows/nodejs-ci.yml
- package.json
- src/common.test.ts
This should handle all of the cases returned by `formatBytes` and hooks up the existing testing environment with Mocha and Chai.
> feat: Add unit test for formatBytes function RM-301

- src/common.ts
- src/constants.ts
- src/gql.ts
- src/private/drives_private.ts
- src/types/base_Types.ts
- src/types/type_conditionals.ts
- src/types/type_guards.ts
- Removes the `string`, `""`, and `"invalid"` from the guard types;
- fixes all compiler errors involved in the change.
I'm still using the `as` keyword, and also using union types with `""` to quick fix the compiler errors **without touching the algorithm**. That would be replaced in an upcoming PR for task RM-304.
> [TASK RM-303] Strict guards

- package.json
- src/constants.ts
This PR increments `ardrive-core-js` to `0.5.0`
`0.4.0` has already been released with a `beta` tag: https://www.npmjs.com/package/ardrive-core-js
> chore(version): Increment version to `0.5.0` PE-96

- src/arweave.ts
This PR fixes the Content-Type tag on file meta tags issue
> fix(file meta data): Use application/json on content-type for meta tags PE-294

- src/ardrive.ts
- src/arfs/arfs_file_wrapper.ts
- src/arfs/arfsdao.ts
- src/exports.ts
- src/types/ardrive_types.ts
- src/types/index.ts
- src/types/upload_conflict_types.ts
- src/utils/error_message.ts
- src/utils/mapper_functions.ts
- src/utils/upload_conflict_resolution.test.ts
- src/utils/upload_conflict_resolution.ts
- tests/integration/ardrive.int.test.ts
This PR adds support the `--ask` option in ArDrive Core. The growing conflict resolution logic has been moved out of the ArDrive method logic and into its own file.
The Core layer defines all of the types for each prompt to implement, which the CLI (or any other app) will optionally implement.
Suggested review order:
```shell
upload_conflict_resolution.test.ts
upload_conflict_resolution.ts
ardrive.int.test.ts
ardrive.ts
```
> PE-639: Ask prompt option on uploads

- package.json
- src/ardrive.ts
- src/ardrive_factory.ts
- src/pricing/ar_data_price_chunk_estimator.ts
- src/pricing/ar_data_price_network_estimator.test.ts
- src/pricing/ar_data_price_network_estimator.ts
This PR replaces the chunk estimator with a new `ARDataPriceNetworkEstimator`. Unfortunately, our assumptions with the arweave pricing algorithm have proven to be false. We are under funding rewards on production.
This new class will cache the pricing results based on how many chunks the byteCount would've been. With chunk based caching we can still be efficient when pricing metaData transactions and base fee transactions. It will get the cached value or simply call the gateway directly if a cached price is not found.
Since this is a hot-fix with the base branch of `master`, here are the proposed GitHub release notes:
- Price estimator now gathers and caches prices directly from the gateway
> PE-821: Incorrect price estimation

- package.json
- yarn.lock
GitHub Release:
- `arweave-js` version is now locked to `1.10.18`
> chore(deps): Lock arweave version PE-843

- src/ardrive.ts
- src/arfs/arfs_entity_name_validators.test.ts
- src/arfs/arfs_entity_name_validators.ts
- tests/integration/ardrive.int.test.ts
This PR is heavily based on @matibat work on rename files, folders and drives feature and #143 
- improves ArFS entity name validators tests making them parameterized
- add drive name validation to `createPublicFolder` and `createPrivateFolder` integration tests
- add drive name validation to folder creation methods
>  PE-929: validate folder name when creating new folders

- src/ardrive.ts
- src/arfs/arfs_entity_name_validators.test.ts
- src/arfs/arfs_entity_name_validators.ts
- tests/integration/ardrive.int.test.ts
This PR is heavily based on @matibat work on rename files, folders and drives feature.
- improves ArFS entity name validators tests making them parameterized
- add drive name validation to `createPublicDrive` and `createPrivateDrive` integration tests
- add drive name validation to drive creation methods
> PE-928: validate drive name when creating new drives

- package.json
- src/ardrive.ts
This PR fixes private folder uploads that contain files within them.
GH Release Notes:
- Bulk folder uploads to a private drive will no longer throw errors
> PE-967: Fix priv folder uploads

- package.json
- src/ardrive.ts
This PR sends the contents of a folder upload to the correct destination folder.
GitHub Release Notes:
- File contents of a folder upload will now correctly be uploaded inside of that folder on chain
> PE-979: fix folder upload contents target

- src/ardrive.ts
- src/arfs/arfs_entity_name_validators.test.ts
- src/arfs/arfs_entity_name_validators.ts
- tests/integration/ardrive.int.test.ts
This PR is based on #145 
- add `assertNamesWithinFolder` helper function and update unit tests
- add folder and file name validation to `createPublicFolderAndUploadChildren` and `createPrivateFolderAndUploadChildren` and create integration tests for both methods (just testing folder and name validation as they will be deprecated)
> PE-930: validate names within folder

- src/arfs/arfs_entity_name_validators.test.ts
- src/arfs/arfs_entity_name_validators.ts
- tests/integration/ardrive.int.test.ts
It removes some entity name rules. As we have less rules I thought it would be good to add those 3 invalid name cases to all our integration tests.
> PE-983: Update entity name validation rules

- src/arfs/arfs_entity_name_validators.test.ts
- src/arfs/arfs_entity_name_validators.ts
- tests/integration/ardrive.int.test.ts
Change the validation for max file name character length to max 255 bytes
Update all integration tests using `assertEntityNameExpectations` helper
Alphabetical sorting on imports
> PE-795: file name byte length

- README.md
- src/arfs/arfs_transaction_uploader.ts
- src/arfs/arfsdao.ts
- src/arfs/multi_chunk_tx_uploader.ts
- src/utils/constants.ts
This PR adds a debounced progress callback to the concurrent tx uploader which can currently be enabled with an ENV variable, similar to the persistent cache pattern
> PE-1086: Progress callback on tx uploader

- README.md
This PR adds a few basic examples of how to interact with ArDrive Core JS as a dependency.
> PE-714: Basic README examples for integrating with ArDrive Core

- src/arfs/arfsdao.ts
- src/arfs/multi_chunk_tx_uploader.ts
- src/utils/constants.ts
- src/utils/gateway_api.test.ts
- src/utils/gateway_api.ts
This PR extracts the gateway retry logic into a central class that can be re-used for retrying all requests.
> PE-1112: Gateway API refactor

- tests/helpers/arlocal_test_assertions.ts
- tests/integration/arlocal.int.test.ts
This PR covers the valid JSON types in arlocal integration and removes the ArLocal dependency to a Verto network request for the community contract
> PE-1913: cover json types

- src/arfs/arfs_meta_data_factory.ts
- src/types/custom_metadata_types.ts
- tests/helpers/arlocal_test_assertions.ts
- tests/integration/arlocal.int.test.ts
Changes:
- Follows up the work of Custom Metadata by implementing the WRITE-only side at CORE
Note: Read-only and CLI side will be implemented in another Story
> PE-1534: custom metadata (CORE only)

- package.json
- src/community/ardrive_community_oracle.ts
- src/community/arns_microservice_contract_oracle.ts
- src/community/pds_contract_oracle.ts
- src/exports.ts
- tests/integration/arlocal.int.test.ts
this PR fixes an issue we're seeing with the default contract reader when fetching the ardrive contract when determining the community tip during uploads
as we were forewarned, it seems the Verto contract cache is no longer publicly available. fortunately PDS is now hosting our own contract cache, the ArNS Microservice -- here we switch to using that cache
> fix(contract reader): switch to a PDS managed default contract cache

- package.json
- src/ardrive.ts
- src/arfs/arfsdao.ts
- src/types/entity_key.test.ts
- src/types/gql_Types.ts
- src/utils/gateway_api.ts
- tests/integration/ardrive.int.test.ts
- tests/integration/arlocal.int.test.ts
- Provide better GQL error message on GQL timeouts
- Remove owner assertions when using JWK constructed ArDrive Class
- This will prevent unnecessary read queries for the original owner of the drive which can scale poorly with large drive sizes
> chore: release 2.0.3

- package.json
- src/arfs/arfsdao.ts
- src/arfs/arfsdao_anonymous.ts
This PR introduces a mechanism to skip entities that are broken due to an incorrect privacy state. When an entity is determined to be broken, a log entry will be created in the terminal to notify the user of the issue.
1. Added logging functionality to output broken entity information to the 
2. Example log entry:
> fix(list-folders)

- package.json
- src/arfs/arfs_builders/arfs_file_builders.test.ts
- src/arfs/arfs_builders/arfs_file_builders.ts
- src/arfs/arfsdao.ts
- src/arfs/arfsdao_anonymous.test.ts
- src/arfs/arfsdao_anonymous.ts
- src/types/exceptions.ts
- Introduced `FileBuilderValidation` Class: This class throws an error listing all missing file properties, ensuring thorough validation.
- Updated Folder Mounting: Files with any missing property are now skipped when mounting the folder, improving reliability.
> PE-7146: skip files missing data content type while listing folders and drives

- src/ardrive_factory.ts
- src/arfs/arfs_file_wrapper.ts
- src/arfs/turbo.ts
- src/pricing/ar_data_price_chunk_estimator.ts
- src/utils/bundle_packer.ts
- src/utils/constants.ts
this PR restores exported vars for backwards compat:
- `turboProdUrl`
- `turboSettings.turbUrl`
and runs prettier format
> refactor: restore factory-backwards-compat PE-4841

- src/arfs/arfs_file_wrapper.test.ts
- src/arfs/arfs_file_wrapper.ts
- src/arfs/arfs_upload_planner.test.ts
- src/arfs/tx/arfs_prototypes.ts
- tests/integration/ardrive.int.test.ts
- tests/integration/arlocal.int.test.ts
Fixes bug where lastModifiedDate was divided by 1000, causing dates to display as Jan 21, 1970. ArFS spec expects timestamps in milliseconds.
> fix: use milliseconds for manifest timestamps instead of seconds
